#!/bin/bash

yum groupinfo "Network Infrastructure Server"
yum install bind bind-chroot

# With the bind-chroot, these files share the same inode:
ls -id /var/named/chroot/etc/named.conf
ls -id /etc/named.conf

# Backup config file - SELinux context and group ownership are necessary:
cp -a /etc/named.conf /etc/named.conf.bak

# Caching-only DNS server
# /etc/named.conf:
# Enter the ipaddr of the localhost as follows.
listen-on port 53 { 127.0.0.1; 192.168.0.12; };
# Enter the network address as follows.
allow-query     { localhost; 192.168.0.0/24; };

# Forwarding-only DNS server
# /etc/named.conf:
# Enter the ipaddr of the localhost as follows.
listen-on port 53 { 127.0.0.1; 192.168.0.12; };
# This will be the only directive after directory in the options section:
forward only;
forwarders {
8.8.8.8;
};

/etc/init.d/named start
chkconfig named on

rndc status  # display status of the server
rndc stop  # save pending updates and stop
rndc flush  # flush the server’s cache
rndc reload  # reload configuration and zones
